version: '3.9'

services:
  traefik:
    image: traefik:v3.0
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./dynamic:/etc/traefik/dynamic:ro

  blue:
    image: blue
    ports:
      - 8081:80

  whoami:
    image: traefik/whoami
    ports:
      - 8082:80